### PR TITLE
Updates including Kashmiri examples from Richard

### PR DESCRIPTION
**Pull request by aphillips**
Edits to address my action item. In this case, borrowing from @r12a's Kashmiri document (plus a few other minor edits).

@r12a Please review for veracity!

### CODE REVIEW

**Comment by aphillips** [comment]
Have a look. Thinking we might merge this in and then get comments.

Do you have a handy example of Arabic with/without short vowels (to use in Example 7)?

**Comment by aphillips** [comment]
@r12a Could you have a look at this again? Note in particular the Gujarati example. If you have an example of a Gujarati word with varied handling thanks to anuswara/visarga/etc. that would be helpful. (Or other examples in other languages). I think this is close to being ready to commit ?

**Comment by r12a** [comment]
> In an additional twist to this story, two diacritics with different code points could be used here. In our previous example we used ं [U+0902 DEVANAGARI SIGN ANUSVARA ] to represent the nasal sound because the accompanying vowel-sign rises above the hanging baseline. If the vowel-sign was one that didn't rise above the hanging baseline, we would normally use ँ [U+0901 DEVANAGARI SIGN CANDRABINDU ] instead. The function of both of these diacritics is the same, but their code points are different.

I think this gives the wrong impression. The anusvara in 'hindi' represents an 'n' sound, rather than nasalisation. Candrabindu is a _nasalisation_ mark, and not an alternative for a syllable-final 'n' (there is no nasalisation in 'hindi').  In principle, the anusvara is an alternative for candrabindu when space is constrained, but not the other way around. That said, it does sometimes appear to be the case that some words _are_ spelled as if they were nasalised, or alternatively as if they had a syllable-final nasal, eg. snake at https://r12a.github.io/scripts/devanagari/hi.html#nasalisation  I don't believe that applies to the word 'hindi' though.

**Comment by r12a** [comment]
> The alternative use of either a letter or a diacritic for syllable-final nasals is common to many other Indian languages. In addition to Devanagari (used to write languages such as Hindi (language tag hi) or Marathi (language tag mr), scripts such as Malayalam, Gujarati, Odia, and others provide similar spelling options.

[1] i'd say 'several' rather than 'many'

[2] your parens are not properly balanced

[3] The Gujarati example is basically the same as the Devanagari one.  Is there not a different kind of spelling difference in the CDAC doc that we can use?

**Comment by aphillips** [comment]
> I think this gives the wrong impression. The anusvara in 'hindi' represents an 'n' sound, rather than nasalisation. Candrabindu is a _nasalisation_ mark, and not an alternative for a syllable-final 'n' (there is no nasalisation in 'hindi'). In principle, the anusvara is an alternative for candrabindu when space is constrained, but not the other way around. That said, it does sometimes appear to be the case that some words _are_ spelled as if they were nasalised, or alternatively as if they had a syllable-final nasal, eg. snake at https://r12a.github.io/scripts/devanagari/hi.html#nasalisation I don't believe that applies to the word 'hindi' though.

Super useful. I'll adjust the example (borrowing from your document)

**Comment by r12a** [comment]
> Users may also create visually identical (or very similar) graphemes from sequences of characters that are deprecated or unexpected by the Unicode Standard. For example, in some fonts it is possible to create something that looks like the independent vowel /au/ using the (normal) ஔ [[U+0B94 TAMIL LETTER AU](https://deploy-preview-14--string-search-w3c.netlify.app/scripts/tamil/block#char0B94)], or by typing two inappropriate individual letters, ஒள [[U+0B92 TAMIL LETTER O](https://deploy-preview-14--string-search-w3c.netlify.app/scripts/tamil/block#char0B92) + [U+0BB3 TAMIL LETTER LLA](https://deploy-preview-14--string-search-w3c.netlify.app/scripts/tamil/block#char0BB3)]. The latter should by avoided by users, but applications will need to decide whether or not to match such aberrations if they appear in the text.

The alternatives you use as examples are neither deprecated nor unexpected by Unicode. They are canonically equivalent precomposed vs decomposed instances.  So, even if Unicode expresses a preference for precomposed it's not really essential to choose one rather than the other, and normalisation will resolve the matching problem.

A much better example would be something like the vowel-sign constructions shown at https://r12a.github.io/scripts/devanagari/hi.html#vowelsign_encoding, https://r12a.github.io/scripts/bengali/bn.html#vowelsign_encoding2 or https://r12a.github.io/scripts/malayalam/ml.html#vowelsign_encoding2 (the first one at the last link is particularly good)

**Comment by r12a** [comment]
> Confusables or spelling errors these can be common in certain kinds of text due to gaps in keyboard support or due to a similarity in appearance

That particular example (with YEH) is a problematic one.  A much better example might be ⑤ at https://r12a.github.io/scripts/arabic/ks.html#confusables (though it may need a little more explanation). See the note for ⑤. You'll need the noto nastaliq font with the language set to ks to see the right glyph for the sukun (circumflex).  Examples of that confusion/workaround are easy to find in the wild.

**Comment by aphillips** [comment]
> [3] The Gujarati example is basically the same as the Devanagari one. Is there not a different kind of spelling difference in the CDAC doc that we can use?

I don't know. Most of the examples seem to be about nasals, but some are unlabeled.

**Comment by aphillips** [comment]
> The alternatives you use as examples are neither deprecated nor unexpected by Unicode.

I think this text is verbatim from you? 😉 I'll change to the new example you suggest.

**Comment by r12a** [comment]
> I think this text is verbatim from you? 😉 I'll change to the new example you suggest.

Oh, if it is then let me know where you got it from.  Here's the appropriate section in my Tamil notes: https://r12a.github.io/scripts/tamil/ta.html#standalone_encoding  I don't see that text anywhere else in the Tamil page.

**Comment by aphillips** [comment]
@r12a Another look? I'd like to start the year with this merged in... ;-)

**Comment by aphillips** [comment]
Merging per telecon of 2022-12-15

**Pull request merged**
