### PR TITLE
I18N-ACTION-873 plus edits to make doc ready for development

### PR DESCRIPTION
**Pull request by aphillips**
See commit messages, particularly 7fa7b39.

### CODE REVIEW

**Comment by xfq** [comment]
* Preview: https://raw.githack.com/aphillips/string-search/gh-pages/index.html
* Diff: https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fw3c.github.io%2Fstring-search%2F&doc2=https%3A%2F%2Fraw.githack.com%2Faphillips%2Fstring-search%2Fgh-pages%2Findex.html

**Review by r12a — APPROVED** [review]

**Comment by aphillips** [comment]
Addressed https://github.com/w3c/string-search/pull/7/#commitcomment-37967780 when I did the conflict resolution.

**Comment by r12a** [comment]
Ah, but i just realised that of course it still points to our tracker issues, rather than the actual issues. Oh well.  It's probably fine, since we're going to resolve those issues very soon, right? ;-)

Let's just merge this. (Though i think it would be good to make the change suggested by @xfq too.)

**Comment by aphillips** [comment]
I made @xfq's change (unless I missed one). It does point to our tracker--all of the issues are closed, btw. It's really kind of a reference and we should probably turn the comments in the issues into text. In fact I just raised #8 to do that.

**Pull request merged**
